import { execFile } from "node:child_process";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";
import { promisify } from "node:util";

const run = promisify(execFile);
const REPO_ROOT = process.cwd();

async function gitIn(cwd: string, args: string[]): Promise<string> {
  const { stdout } = await run("git", args, { cwd });
  return stdout.trim();
}

async function gh(args: string[]): Promise<string> {
  const { stdout } = await run("gh", args, { cwd: REPO_ROOT });
  return stdout.trim();
}

function pascalCase(slotId: string): string {
  return slotId
    .split("-")
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
}

/**
 * Opens a real PR for a deployed evolution. Does all git work in a throwaway
 * worktree — never switches the branch of the live dev server's own checkout,
 * since that working directory is actively being served while this runs.
 */
export async function openEvolutionPR(params: {
  slotId: string;
  version: number;
  title: string;
  reasoning: string;
  code: string;
}): Promise<{ branch: string; prUrl: string; filePath: string }> {
  const { slotId, version, title, reasoning, code } = params;
  const branch = `evo/${slotId}-v${version}`;
  const relativePath = join("src/components/slots/generated", `${pascalCase(slotId)}.v${version}.tsx`);
  const worktreeDir = join(tmpdir(), `evoweb-worktree-${slotId}-v${version}-${Date.now()}`);

  const baseBranch = await gitIn(REPO_ROOT, ["rev-parse", "--abbrev-ref", "HEAD"]);

  await gitIn(REPO_ROOT, ["worktree", "add", "-b", branch, worktreeDir, baseBranch]);
  try {
    const filePath = join(worktreeDir, relativePath);
    await mkdir(dirname(filePath), { recursive: true });
    const archived = [
      `// Generated by the EvoWeb evolution engine — slot "${slotId}", version ${version}.`,
      `// ${title}`,
      `// ${reasoning}`,
      `//`,
      `// This file is an audit-trail archive of what was verified and deployed at runtime;`,
      `// it is not imported by the running app (slots render from the database at runtime).`,
      "",
      code,
      "",
      "export default Component;",
      "",
    ].join("\n");
    await writeFile(filePath, archived, "utf8");

    await gitIn(worktreeDir, ["add", relativePath]);
    await gitIn(worktreeDir, ["commit", "-m", `evo: ${title} (${slotId} v${version})`]);
    await gitIn(worktreeDir, ["push", "-u", "origin", branch]);

    const prUrl = await gh([
      "pr",
      "create",
      "--title",
      `evo: ${title}`,
      "--body",
      `${reasoning}\n\nOpened automatically by the EvoWeb evolution engine after passing sandbox verification.`,
      "--base",
      baseBranch,
      "--head",
      branch,
    ]);

    return { branch, prUrl: prUrl.trim(), filePath: relativePath };
  } finally {
    await gitIn(REPO_ROOT, ["worktree", "remove", worktreeDir, "--force"]).catch(() => {});
    await rm(worktreeDir, { recursive: true, force: true }).catch(() => {});
  }
}

export async function mergePR(prUrl: string): Promise<void> {
  await gh(["pr", "merge", prUrl, "--squash", "--delete-branch"]);
}

export async function commentOnPR(prUrl: string, comment: string): Promise<void> {
  await gh(["pr", "comment", prUrl, "--body", comment]);
}
